---
services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/breno/media/library:/config
      - /home/breno/media/series:/series
      - /home/breno/media/filmes:/filmes
      - /home/breno/media/fotos:/fotos
    restart: unless-stopped